baseURL = "https://goofy-noyce-1a9fa3.netlify.app/"
languageCode = "en-us"
title = "Test JSX"

theme="jsx-theme"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
